runtime: nodejs10
#api_version: 1
service: default
#threadsafe: yes

env_variables:
  EMAIL: "testingsoftthree@gmail.com"
  PASSWORD: "123testing"
  STRIPE_KEY: "sk_test_51HfgSrIoqQ2sulu0SLUA2H8Ll1FRtG6kNsZpKq7XtIGyMs7oT8r5KVNGdBJYuzMAFwkKn6gMhPLALxeUO4NvE1Gh00v28RQnIv"
  DB_URL: "mongodb+srv://akbar:akbar123@cluster0.flazf.mongodb.net/athens?retryWrites=true&w=majority"
  SECRET_KEY: "thesecretekey"
  EXPIRES_IN: "365d"
  OAUTH_CLIENTID: "975316159704-rak1rsj1ge8q1ma4l4jhobncviqrhvh9.apps.googleusercontent.com"
  OAUTH_CLIENT_SECRET: "CLc5l-7RUVrc7DUbINtOqzcp"
  OAUTH_REFRESH_TOKEN: "1//04EM6vjTUdh9zCgYIARAAGAQSNwF-L9Irf0l9bUSWF0Mu8xA7L6g1t3J4dyGC5G4yS9Si09pflOvfeBDmuWd1A1e8kBOkaUixWEc"